apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: initialize-telemetry-workspace
spec:
  params:
  - name: telemetry_filename
    type: string
  - name: mount_path
    type: string
  - name: pipelineRun_name
    type: string

  steps:
    - name: initialize-telemetry-workspace
      image: alpine
      script: |
        #!/bin/sh

        mkdir -p $(params.mount_path)/$(params.pipelineRun_name)/telemetry/
        mkdir -p $(params.mount_path)/$(params.pipelineRun_name)/raw/
        mkdir -p $(params.mount_path)/$(params.pipelineRun_name)/quicklook/
        mkdir -p $(params.mount_path)/$(params.pipelineRun_name)/logs/

        cp $(params.mount_path)/data/$(params.telemetry_filename) $(params.mount_path)/$(params.pipelineRun_name)/telemetry/

  workspaces:

    - name: local-workspace
      mountPath: $(params.mount_path)
