apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: raw2quicklook
spec:
  params:
  - name: input_dir
    type: string
  - name: output_dir
    type: string
  - name: log_dir
    type: string
  steps:
    - name: process
      image: emilfazzi/raw2quicklook:latest
      resources:
       limits:
         cpu: 2000m
      script: |
        #!/bin/sh
        pwd
        ls -alR /usr/src/
        python3 raw2quicklook.py --input /tmp/workspace/$(params.input_dir) --output /tmp/workspace/$(params.output_dir) --log /tmp/workspace/$(params.log_dir) 
  
  workspaces:
    - name: output
      description: |
        Workspace of a single run
      mountPath: /tmp/workspace
      optional: false