apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: telemetry2raw
spec:
  params:
  - name: input_dir
    type: string
  - name: output_dir
    type: string
  - name: log_dir
    type: string
  - name: pipelineRun_name
    type: string
  steps:
    - name: process
      image: emilfazzi/telemetry2raw:latest
      resources:
       limits:
         cpu: 6000m

      script: |
        #!/bin/sh
        python3 tm2raw.py --input /tmp/workspace/$(params.pipelineRun_name)/$(params.input_dir) --output /tmp/workspace/$(params.pipelineRun_name)/$(params.output_dir) --log /tmp/workspace/$(params.pipelineRun_name)/$(params.log_dir) 
  
  workspaces:
    - name: output
      description: |
        Workspace of a single run
      mountPath: /tmp/workspace
      optional: false
