apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tester
spec:
  params:
  - name: custom_dir
    type: string
  - name: message
    type: string
    default: "default"
  steps:
    - name: process
      image: alpine
      script: |
        #!/bin/sh
        echo "$(params.message)"
        ls -alR $(params.custom_dir)

  workspaces:
    - name: output
      description: |
        Workspace of a single run
      mountPath: $(params.custom_dir)
      optional: false
