apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tester-touch
spec:
  steps:
    - name: tester-touch
      image: ubuntu
      script: |
        #!/bin/sh
        touch /tmp/workspace/example_file

  workspaces:
    - name: output
      description: |
        Workspace of a single run
      mountPath: /tmp/workspace/
      optional: false
