apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: initialize-telemetry-workspace
spec:
  params:
  - name: telemetry_filename
    type: string
  - name: mount_path
    type: string

  steps:
    - name: initialize-telemetry-workspace
      image: alpine
      script: |
        #!/bin/sh
        mkdir $(params.mount_path)/telemetry/
        mkdir $(params.mount_path)/raw/
        mkdir $(params.mount_path)/quicklook/
        mkdir $(params.mount_path)/logs/

        # cp /root/workspace/$(params.telemetry_filename) $(params.mount_path)/telemetry/

  workspaces:
    # - name: input
    #   description: |
    #     Workspace of a single run
    #   mountPath: /root/workspace/
    #   optional: false

    - name: local-workspace
      mountPath: $(params.mount_path)
