apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tester
spec:
  params:
  - name: custom_dir
    type: string
  steps:
    - name: process
      image: emilfazzi/tester:latest
      script: |
        #!/bin/sh
        python3 tester.py --directory $(params.custom_dir)

  workspaces:
    - name: output
      description: |
        Workspace of a single run
      mountPath: $(params.custom_dir)
      optional: false
