apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: tester-task-run
spec:
  taskRef:
    name: tester
  workspaces:
    - name: output  # this workspace name must be declared in the Task
      mountPath: /tmp/workspace/ 