apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  namespace: tekton-dashboard
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
