apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: telemetry2raw-raw2quicklook
spec:
  params:
  - name: telemetry_filename
    type: string
  - name: pipelineRun_name
    type: string

  tasks:
    - name: initialize
      taskRef:
        name: initialize-telemetry-workspace
      params:
      - name: telemetry_filename
        value: $(params.telemetry_filename)
      - name: mount_path
        value: "/root/local-workspace/"
      - name: pipelineRun_name
        value: $(params.pipelineRun_name)
      workspaces:
        - name: local-workspace
          workspace: pipeline-io

    - name: telemetry2raw-task
      taskRef:
        name: telemetry2raw
      params:
        - name: input_dir
          value: "telemetry/"
        - name: output_dir
          value: "raw/"
        - name: log_dir
          value: "logs/"
        - name: pipelineRun_name
          value: $(params.pipelineRun_name)
      runAfter:
        - initialize
      workspaces:
        - name: output
          workspace: pipeline-io

    - name: raw2quicklook-task
      taskRef:
        name: raw2quicklook
      params:
        - name: input_dir
          value: "raw/"
        - name: output_dir
          value: "quicklook/"
        - name: log_dir
          value: "logs/"
        - name: pipelineRun_name
          value: $(params.pipelineRun_name)
      runAfter:
        - telemetry2raw-task
      workspaces:
        - name: output
          workspace: pipeline-io
      

  workspaces:
    - name: pipeline-io
