apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: telemetry2raw-raw2quicklook
spec:
  params:
  - name: telemetry_filename
    type: string

  tasks:
    - name: initialize
      taskRef:
        name: initialize-telemetry-workspace
      params:
      - name: telemetry_filename
        value: $(params.telemetry_filename)
      - name: mount_path
        value: "/root/local-workspace/"
        
      workspaces:
        - name: local-workspace
          workspace: pipeline-io

    # - name: tester-post
    #   taskRef:
    #     name: tester
    #   params:
    #   - name: custom_dir
    #     value: "/tmp/workspace/"
    #   runAfter:
    #     - initialize
    #   workspaces:
    #     - name: output
    #       workspace: pipeline-io

    - name: telemetry2raw-task
      taskRef:
        name: telemetry2raw
      params:
        - name: input_dir
          value: "telemetry/"
        - name: output_dir
          value: "raw/"
        - name: log_dir
          value: "logs/"
      runAfter:
        - initialize
      workspaces:
        - name: output
          workspace: pipeline-io

    - name: raw2quicklook-task
      taskRef:
        name: raw2quicklook
      params:
        - name: input_dir
          value: "raw/"
        - name: output_dir
          value: "quicklook/"
        - name: log_dir
          value: "logs/"
      runAfter:
        - telemetry2raw-task
      workspaces:
        - name: output
          workspace: pipeline-io
      

  workspaces:
    - name: pipeline-io
