apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: touch-read-file
spec:
  params:
  - name: pipelineRun_name
    type: string
  tasks:
    - name: tester-before
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"
      - name: message
        value: $(params.pipelineRun_name)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: tester-touch
      taskRef:
        name: tester-touch
      runAfter: 
        - tester-before
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: tester-post
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"
      - name: messgage
        value: "test"
      runAfter:
        - tester-touch
      workspaces:
        - name: output
          workspace: pipeline-workspace

  workspaces:
    - name: pipeline-workspace