apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: telemetry2raw-raw2quicklook
spec:
  params:
  - name: telemetry_filename
    type: string

  tasks:
    - name: initialize
      taskRef:
        name: testinitialize-telemetry-workspaceer
      params:
      - name: workspace_path
        value: "/tmp/workspace/$(context.pipelinerun.uid)/"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: telemetry2raw-task
      taskRef:
        name: telemetry2raw
      params:
        - name: input_dir
          value: "/tmp/workspace/data"
        - name: output_dir
          value: "/tmp/workspace/raw"
        - name: log_dir
          value: "/tmp/workspace/raw"
      runAfter:
        - tester-pre
      workspaces:
        - name: output
          workspace: pipeline-workspace
      
    - name: tester-post
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/raw"
      runAfter:
        - telemetry2raw-task
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: goodbye
      runAfter:
        - telemetry2raw-task
      taskRef:
        name: goodbye
      params:
      - name: username
        value: "CIAO"

  workspaces:
    - name: pipeline-workspace
