apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: touch-read-file
spec:
  tasks:
    - name: tester-before
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"

    - name: tester-touch
      taskRef:
        name: tester-touch
      runAfter: 
        - tester-before

    - name: tester-post
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"
      runAfter:
        - tester-touch

  workspaces:
    - name: workspace
      description: |
        The folder where we write the message to. If no workspace
        is provided then the message will not be written.        
      mountPath: /home/emilfazzi/workspace