apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: touch-read-file
spec:
  tasks:
    - name: tester-before
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: tester-touch
      taskRef:
        name: tester-touch
      runAfter: 
        - tester-before
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: tester-post
      taskRef:
        name: tester
      params:
      - name: custom_dir
        value: "/tmp/workspace/"
      runAfter:
        - tester-touch
      workspaces:
        - name: output
          workspace: pipeline-workspace

  workspaces:
    - name: pipeline-workspace